name: Note-App

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Notes are ready"

      # - name: Simulate an error
      #   run: echo "About to fail" ; exit 1

      - name: Another greeting
        run: echo "Notes are taken!"